In [1]:
import pandas as pd

# US States
Postal and 2-digit FIPS codes for 50 US states, DC and territories (Samoa, Guam, Mariana Island, Puerto Rico and Virgin Islands)

In [2]:
state_fips = pd.read_csv('fips_states.csv')
state_fips

                       state state_code  fips
0                    Alabama         AL     1
1                     Alaska         AK     2
2                    Arizona         AZ     4
3                   Arkansas         AR     5
4                 California         CA     6
5                   Colorado         CO     8
6                Connecticut         CT     9
7       District of Columbia         DC    11
8                   Delaware         DE    10
9                    Florida         FL    12
10                   Georgia         GA    13
11                    Hawaii         HI    15
12                     Idaho         ID    16
13                  Illinois         IL    17
14                   Indiana         IN    18
15                      Iowa         IA    19
16                    Kansas         KS    20
17                  Kentucky         KY    21
18                 Louisiana         LA    22
19                     Maine         ME    23
20                  Maryland         MD    24
21             Massachusetts         MA    25
22                  Michigan         MI    26
23                 Minnesota         MN    27
24               Mississippi         MS    28
25                  Missouri         MO    29
26                   Montana         MT    30
27                  Nebraska         NE    31
28                    Nevada         NV    32
29             New Hampshire         NH    33
30                New Jersey         NJ    34
31                New Mexico         NM    35
32                  New York         NY    36
33            North Carolina         NC    37
34              North Dakota         ND    38
35                      Ohio         OH    39
36                  Oklahoma         OK    40
37                    Oregon         OR    41
38              Pennsylvania         PA    42
39              Rhode Island         RI    44
40            South Carolina         SC    45
41              South Dakota         SD    46
42                 Tennessee         TN    47
43                     Texas         TX    48
44                      Utah         UT    49
45                   Vermont         VT    50
46                  Virginia         VA    51
47                Washington         WA    53
48             West Virginia         WV    54
49                 Wisconsin         WI    55
50                   Wyoming         WY    56
51            American Samoa         AS    60
52                      Guam         GU    66
53  Northern Mariana Islands         MP    69
54               Puerto Rico         PR    72
55            Virgin Islands         VI    78

# US Counties
County 4-digit FIPS codes and names for 50 US states, DC and territories (Samoa, Guam, Mariana Island, Puerto Rico and Virgin Islands)

In [3]:
county_fips = pd.read_csv('fips_counties.csv')
county_fips.head()

   fips    county state  state_fips
0  1001  Autauga     AL           1
1  1003  Baldwin     AL           1
2  1005  Barbour     AL           1
3  1007     Bibb     AL           1
4  1009   Blount     AL           1

# US Cities
Data from simplemaps.com for all incorporated US cities (includes DC and Puerto Rico). Includes state, county, coordinates, zip codes and some demographic info. Does not include unincorporated cities.

In [4]:
cities = pd.read_csv('simplemaps_uscities_basicv1.6/uscities_2019-09.csv')
cities.head()

,city,city_ascii,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,South Creek,South Creek,WA,Washington,53053,Pierce,53053,Pierce,46.9994,-122.3921,2500.0,125.0,polygon,False,True,America/Los_Angeles,3,98580 98387 98338,1840042075
1,Roslyn,Roslyn,WA,Washington,53037,Kittitas,53037,Kittitas,47.2507,-121.0989,947.0,84.0,polygon,False,True,America/Los_Angeles,3,98941 98068 98925,1840019842
2,Sprague,Sprague,WA,Washington,53043,Lincoln,53043,Lincoln,47.3048,-117.9713,441.0,163.0,polygon,False,True,America/Los_Angeles,3,99032,1840021107
3,Gig Harbor,Gig Harbor,WA,Washington,53053,Pierce,53053,Pierce,47.3352,-122.5968,9507.0,622.0,polygon,False,True,America/Los_Angeles,3,98332 98335,1840019855
4,Lake Cassidy,Lake Cassidy,WA,Washington,53061,Snohomish,53061,Snohomish,48.0639,-122.0920,3591.0,131.0,polygon,False,True,America/Los_Angeles,3,98223 98258 98270,1840041959